Page service
OrcestraGamificacao/site-front pull request #60
Opened 2019-08-21 16:37 UTC by alan-ms

## Issue #

#44 
## Descrição

Criação da página de serviços de acordo com o protótipo e descrição da Issue.
## Screenshots (se apropriado):
![Screenshot from 2019-08-21 13-31-43](https://user-images.githubusercontent.com/35638067/63450640-caab6480-c418-11e9-946c-4dda9901c93b.png)

2019-08-21 20:12 UTC, filipetoyoshima requested changes
- Se eu scrollar até o fim da `home` e depois clicar em `Serviços`, na navbar, eu sou redirecionado para fim da página de serviços. O correto deveria ser sempre começar pelo início da página.

- O Componente `btnServices` deve levar à página de serviços

2019-08-22 18:16 UTC, filipetoyoshima requested changes
![image](https://user-images.githubusercontent.com/29482983/63539111-b7b79380-c4ef-11e9-8acf-67c3155c6f30.png)

Os créditos da imagem estão bem menores do que no Screenshot, quais ilegíveis aqui. Tem ideia do que pode ter causado essa diferença?

2019-08-23 12:58 UTC, alan-ms commented
Feita correção no tamanho da fonte do texto de crédito. 

![image](https://user-images.githubusercontent.com/35638067/63594331-8ccf4d00-c58c-11e9-8959-7d9629f64c25.png)

2019-08-23 13:24 UTC, filipetoyoshima approved these changes

2019-08-23 13:24 UTC, merged